# Generated by Django 2.1.7 on 2019-03-26 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='email',
            new_name='emailAddress',
        ),
    ]
